MDScreen:
    MDBoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation:'horizontal'
            size_hint: .1,.1
            Label:
                text: 'Gestionando Salas'
                text_size: 4 , 5
                color: 
                
        GridLayout:
            cols:2
            rows:3
            Button:
                text:'opcion 1'
                #size_hint: .7, .7
            TextInput:
            Button:
                text:'opcion 2'
                #size_hint: .5, .5
            TextInput:
            Button:
                text:'opcion 3'
                #size_hint: .5, .5
            TextInput:
